### PR TITLE
fix rejection if not number for french phone

### PR DESCRIPTION
**Pull request by MaximeThoonsen**
## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Yes I wrote a unit test

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by psanders — COMMENTED** [review]
@MaximeThoonsen, the fix looks great. I can see that it improves validation for UK numbers as well. I'm ready to merge this.

Are you able to sign the CLA?

**Comment by MaximeThoonsen** [comment]
@psanders Yes I can. How I can do it? 
You can merge it with your own commit if it's easier

**Comment by psanders** [comment]
Hey @MaximeThoonsen, to sign the CLA, you only need to write a comment right here saying:

"I have read the CLA Document, and I hereby sign the CLA."

I know it can be a bit confusing, so [here](https://github.com/fonoster/fonoster/pull/484) is an example.

**Comment by MaximeThoonsen** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Pull request merged**
