### PR TITLE
change copyright year

### PR DESCRIPTION
**Pull request by 0o001**
## Description
https://github.com/search?q=repo%3Afonoster%2Ffonoster%20by%20Fonoster%20Inc%20(https%3A%2F%2Ffonoster.com)&type=code

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by 0o001** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/fonoster/fonoster/blob/main/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the CLA Document and I hereby sign the CLA

**Comment by 0o001** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/fonoster/fonoster/blob/main/cla.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

recheck

**Comment by 0o001** [comment]
recheck

**Comment by 0o001** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Comment by 0o001** [comment]
recheck

**Comment by 0o001** [comment]
recheck

**Comment by psanders** [comment]
Hey @0o001 thanks for putting this together. However, the `<%= YEAR %>` is needed for templating purposes. Thanks again.

**Pull request closed without merging**
