### PR TITLE
Add myself to beta users

### PR DESCRIPTION
**Pull request by scshiv29-dev**

### CODE REVIEW

**Comment by scshiv29-dev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by scshiv29-dev** [comment]
recheck

**Comment by scshiv29-dev** [comment]
recheck

**Comment by psanders** [comment]
Welcome to the private beta 😀

Please post on the Slack channel or the [GH Discussion](https://github.com/fonoster/fonoster/discussions/209) if you have any questions.

**Pull request merged**
