### PR TITLE
feat: add * to active project cli projects:ls

### PR DESCRIPTION
**Pull request by xquanluu**
#445 Hi @YuriCodes 

Please help me to review and give comment. I checked the payload for projects endpoint:

{
"ref":"PJ63732ecf28f2330007d97bbd",
"name":"TestProject",
"userRef":"US63732bcfa978a700071b7641",
"accessKeyId":"PJ63732ecf28f2330007d97bbd",
"accessKeySecret":"asdasd",
"allowExperiments":true,
"createTime":"2022-11-15T06:16:47.640Z",
"updateTime":"2022-11-19T23:57:36.841Z"
}

There is no attribute to tell me which one is default. so I assume the first project is the default.

I'm trying to use [https://oclif.io/docs/testing](@oclif/test) to test command but it's conflicting with our chai expect. If you can give me some hint to add unit test for this then it's great.

Thanks a lot.

### CODE REVIEW

**Comment by psanders** [comment]
Hi @xquanluu 

After you login a file is created at `~/.fonoster/config`. The content of the file looks as follows:

```json
{
 "endpoint": "api.fonoster.net",
 "accessKeyId": "US6191549001b29f0600000001",
 "accessKeySecret": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmb25vc3RlciIsInJvbGUiOiJVU0VSIiwiYWNjZXNzS2V5SWQiOiJVUzYxOTE1NDkwMDFiMjlmMDYwMDAwMDAwMSIsImlhdCI6MTY2ODI3NzU1NCwiZXhwIjoxNjcwODY5NTU0fQ.Ee2LmNMtlQcqx2RmgBUBHOBX0ZRVrxpaYe0SGFcG4y8",
 "defaultProject": {
  "name": "Demo",
  "accessKeyId": "PJ624c4815e645d50006c98e28",
  "accessKeySecret": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJmb25vc3RlciIsInJvbGUiOiJQUk9KRUNUIiwiYWNjZXNzS2V5SWQiOiJQSjYyNGM0ODE1ZTY0NWQ1MDAwNmM5OGUyOCIsImlhdCI6MTY0OTE2NjM1NywiZXhwIjoxNjgwNzIzOTU3fQ.ehjkZ6R9ngtf6nNUafkTaYj7MSHiNwPgH77JRJnuLhA"
 }
}
```

That should aid the decision to mark the active project.

**Comment by xquanluu** [comment]
Thanks @psanders for the hint, 

I updated the PR, please help to review again

**Review by psanders — APPROVED** [review]
Looks great. Thanks again!

**Comment by psanders** [comment]
This looks great. Thanks so much for this contribution.

**Pull request merged**
