### PR TITLE
Adding myself to beta user list.

### PR DESCRIPTION
**Pull request by RiadVargas**

### CODE REVIEW

**Comment by RiadVargas** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by RiadVargas** [comment]
recheck

**Comment by RiadVargas** [comment]
recheck

**Comment by psanders** [comment]
Welcome to the private beta 😀

Please post on the Slack channel or the [GH Discussion](https://github.com/fonoster/fonoster/discussions/209) if you have any questions.

**Pull request merged**
