### PR TITLE
Feature: Add tooltip component

### PR DESCRIPTION
**Pull request by obrucheoghene**
## Description

Created the Tooltip component for the Storybook #677

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Created stories for each usecase

## Checklist:
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

Screenshot 2024-12-23 at 10 57 57 PM

Screenshot 2024-12-23 at 10 58 27 PM

### CODE REVIEW

**Review by psanders — CHANGES_REQUESTED** [review]
Great work here! 

Would you take another pass at the styles? The content of the component seems to be missing space,  on the bottom. 

It happens for both single and multiline. 

Screenshot 2024-12-24 at 7 36 10 PM

**Comment by psanders** [comment]
@obrucheoghene, Also, the triangle on the bottom seems wider in the designs, but I don't know how much control we have over that, and I think it is not a big issue.

**Comment by psanders** [comment]
@obrucheoghene All set here 🙌

**Comment by obrucheoghene** [comment]
Thank you @psanders

**Pull request merged**
