### PR TITLE
Added stop feature for docker

### PR DESCRIPTION
**Pull request by alifiratari**

### CODE REVIEW

**Comment by alifiratari** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alifiratari** [comment]
recheck

**Comment by alifiratari** [comment]
recheck

**Comment by psanders** [comment]
@alifiratari 👋 

This PR looks very straightforward.

I will take a deeper look tonight and come back to you.

Thanks 🙏

**Review by psanders — APPROVED** [review]
I reviewed the PR for a second time. Everything looks good. 

Thanks for submitting this contribution.
__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

**Pull request merged**
