### PR TITLE
Fix: Gather verb example, adding - source: 'dtmf,speech' -

### PR DESCRIPTION
**Pull request by BrayanMnz**
Fix: Gather verb example:
    adding => source: "dtmf,speech"

### CODE REVIEW

**Comment by BrayanMnz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by BrayanMnz** [comment]
recheck

**Comment by nisancigokmen** [comment]
congratulations.good luck. @BrayanMnz

**Comment by psanders** [comment]
Thanks @BrayanMnz it looks good. Merged!

**Pull request merged**
