### PR TITLE
Update betauser.json

### PR DESCRIPTION
**Pull request by alexsands**
- Adds `alexsands` to the beta user list

### CODE REVIEW

**Comment by alexsands** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alexsands** [comment]
recheck

**Comment by alexsands** [comment]
recheck

**Comment by psanders** [comment]
Welcome to the private beta 😀

Please post on the Slack channel or the [GH Discussion](https://github.com/fonoster/fonoster/discussions/209) if you have any questions.

**Pull request merged**
