### PR TITLE
fix:  update build and test scripts to ensure .env file is present

### PR DESCRIPTION
**Pull request by justjordan15**
## Description

build script update: The build script has been modified to check for the existence of the .env file before proceeding with the build. If the file is missing, it copies .env.example.dev to .env

test script update: The test script has been updated to ensure that the .env file is present before running tests. If the .env file is missing, it will display an error message explicitly stating the file is missing and exit the process. This prevents tests from running in an unconfigured environment.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] I have performed a self-review of my code
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by psanders — CHANGES_REQUESTED** [review]
As the project grows, we will have additional preconditions, and it would be beneficial to consolidate everything into a single script.

Please convert the logic into a shell script that checks the precondition and produces a clear error, similar to what you did in the `test` hook.

Place the script inside the ./scripts folder (perhaps named _check-preconditions.sh_) and call the script in the `pretest` hook.

**Review by justjordan15 — COMMENTED** [review]
@psanders I put the script in a folder. Now if test are ran without the .env file it explicitly says to copy the .env file in the root of the project.

**Review by psanders — APPROVED** [review]
Super thankful for this one! You rock 🙌

**Comment by psanders** [comment]
@justjordan15 

This is all good. However, it needs the [DCO](https://github.com/fonoster/fonoster/blob/main/CONTRIBUTING.md#dco) signature.

**Comment by psanders** [comment]
@justjordan15 All set here!

The next person will have a better experience thanks to you 🙌

**Pull request merged**
