### PR TITLE
Update betauser.json

### PR DESCRIPTION
**Pull request by nrjchnd**
Access request to Beta

### CODE REVIEW

**Comment by nrjchnd** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nrjchnd** [comment]
recheck

**Comment by nrjchnd** [comment]
> I have read the CLA Document and I hereby sign the CLA


recheck

**Comment by nrjchnd** [comment]
recheck

**Comment by psanders** [comment]
Welcome to the private beta 😀

Please post on the Slack channel or the [GH Discussion](https://github.com/fonoster/fonoster/discussions/209) if you have any questions.

**Pull request merged**
